### ISSUE TITLE
Code the file select to bind to aurelia, then use the csvjson converter

### ISSUE THREAD

**Issue by JoshuaVSherman** [UltimatePromotions/ourhandsandfeet#196]
http://mounirmesselmeni.github.io/2012/11/20/reading-csv-file-with-javascript-and-html5-file-api/
* want to select a .csv file
* convert it to json
* post the json to the backend to create many books

**Comment by freethlua** [comment]
I see the problem now. 

Generally what I do is avoid using modules that depend on native Node code because Webpack, and client side code will eventually run in the Browser where node wouldn't be available anyways. 

This doesn't apply to `dotenv` as its purpose is only to aid webpack which runs in node env. 

Since `csvtojson` is going to be needed in actually client-side code which will run in a Browser environment, it'll be a problem for it to be accessing native Node modules like `fs`.

There are other modules https://www.npmjs.com/search?q=csvjson that can achieve our purpose that don't depend on native node. This seem good: https://github.com/pradeep-mishra/csvjson

**Comment by JoshuaVSherman** [comment]
Awesome, thanks, I'll change it to that one
